name: Test sofa-setup-action

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  run:
    name: Run on ${{ matrix.os }} with SOFA ${{ matrix.sofa_branch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2016]
        sofa_branch: [master, v21.06]

    steps:
      - name: Set env vars
        shell: bash
        run: |
          # Set env vars
          SOFA_ROOT=/opt/sofa
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            SOFA_ROOT='C:\sofa'
          fi
          echo "SOFA_ROOT=$SOFA_ROOT" | tee -a $GITHUB_ENV

      - name: Setup SOFA and deps
        id: sofa
        uses: guparan/sofa-setup-action@master
        with:
          sofa_version: ${{ matrix.sofa_branch }}
          sofa_root: ${{ env.SOFA_ROOT }}

      - name: Print sofa-setup-action outputs
        shell: bash
        run: |
          echo 'steps.sofa.outputs = ${{ toJSON(steps.sofa.outputs) }}'
          echo "----------------------------"
          ls -la '${{ steps.sofa.outputs.sofa_root }}'
          echo "----------------------------"
          echo "PATH = $PATH"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "----------------------------"
            cmd //c 'echo EIGEN3_ROOT=%EIGEN3_ROOT%'
            cmd //c 'echo Eigen3_ROOT=%Eigen3_ROOT%'
            cmd //c 'echo BOOST_ROOT=%BOOST_ROOT%'
            cmd //c 'echo Boost_ROOT=%Boost_ROOT%'
          fi
          